const express = require("express");
const rp = require("request-promise-native");
const querystring = require("querystring");

require("dotenv").config();
const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;
const USER_NAME = process.env.USER_NAME;

const BASE_LIST_PREFIX = "##";
const MERGED_LIST_SEPERATOR = "&";
const MERGED_LIST_PREFIX = "#*";

const app = express();

app.get("/login", function(req, res) {
	const scopes = "playlist-read-private playlist-modify-public";
	res.redirect(
		"https://accounts.spotify.com/authorize" +
			"?response_type=code" +
			"&client_id=" +
			CLIENT_ID +
			(scopes ? "&scope=" + encodeURIComponent(scopes) : "") +
			"&redirect_uri=" +
			encodeURIComponent("http://localhost:8000/callback")
	);
});

app.get("/callback", (req, res, next) => {
	rp.post({
		url: "https://accounts.spotify.com/api/token",
		form: {
			code: req.query.code,
			grant_type: "authorization_code",
			redirect_uri: "http://localhost:8000/callback"
		},
		headers: {
			Authorization:
				"Basic " +
				Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString("base64")
		},
		json: true
	})
		.then(response => {
			const { access_token, refresh_token } = response;
			res.redirect(
				"http://localhost:8000/mergeplaylists?" +
					querystring.stringify({ access_token, refresh_token })
			);
		})
		.catch(err => {
			console.log({ err });
			res.redirect("http://localhost:8000/home" + querystring.stringify(err));
		});
});

app.get("/home", (req, res, next) => {
	// res.send(req.query);
	res.send(
		"<button onClick=\"fetch('/mergeplaylists')\" >merge playlists </button>  "
	);
});

app.get("/playlists", (req, res, next) => {
	const { access_token } = req.query;
	if (!access_token) {
		res.redirect("/home?err=noToken");
		return;
	}
	rp.get({
		url: "https://api.spotify.com/v1/me/playlists?limit=50",
		headers: {
			Authorization: "Bearer " + access_token
		}
	})
		.then(response => {
			const playlists = JSON.parse(response).items;
			if (!playlists) {
				res.status(404).send();
				return;
			} else {
				res.send(playlists);
			}
		})
		.catch(err => {
			console.log({ err });
			res.redirect("http://localhost:8000/home" + querystring.stringify(err));
		});
});

function combinations(arr) {
	const fn = function(active, rest, a) {
		if (!active.length && !rest.length) return;
		if (!rest.length) {
			a.push(active);
		} else {
			fn(active.concat(rest[0]), rest.slice(1), a);
			fn(active, rest.slice(1), a);
		}
		return a;
	};
	const result = fn([], arr, []);
	return result ? result : [];
}

app.get("/mergeplaylists", async (req, res, next) => {
	console.log("Called mergeplaylists");
	const { access_token } = req.query;
	if (!access_token) {
		res.redirect("/login");
		return;
	} else {
		rp.get(
			"http://localhost:8000/playlists?" +
				querystring.stringify({ access_token })
		)
			.then(async playlists => {
				// extract playlists from response and filter out followed unowned lists
				const owned_lists = JSON.parse(playlists).filter(
					l => l.owner.id === USER_NAME
				);
				// find playlists with prefix
				const base_lists = owned_lists.filter(l =>
					l.name.startsWith(BASE_LIST_PREFIX)
				);
				const merged_lists = combinations(base_lists)
					.filter(lists => lists.length > 1)
					.map(lists => {
						return {
							name:
								MERGED_LIST_PREFIX +
								lists
									.map(l => l.name.slice(BASE_LIST_PREFIX.length))
									.join(MERGED_LIST_SEPERATOR),
							lists: lists
						};
					});
				// loop over all (desired) merged lists
				outer: for (let merged_list of merged_lists) {
					const list_name = merged_list.name;
					// check if there already is a playlist with the right name
					for (let owned_list of owned_lists) {
						if (owned_list.name === list_name) {
							merged_list.id = owned_list.id;
							continue outer;
						}
					}
					// if there is no fitting playlist yet, create one
					console.log("Creating list with name " + list_name);
					const created_list = await rp
						.post({
							url: "https://api.spotify.com/v1/me/playlists",
							headers: {
								Authorization: "Bearer " + access_token,
								"Content-Type": "application/json"
							},
							body: JSON.stringify({
								name: list_name,
								description: "Automatically generated by playlist_merger"
							})
						})
						.catch(err => {
							throw err;
						});
					merged_list.id = JSON.parse(created_list).id;
				}
				// get track uris of songs in every base list
				const tracks = {};
				for (let list of base_lists) {
					let response = {
						next:
							list.tracks.href +
							"?" +
							querystring.stringify({
								fields: "total,next,items(track(uri))"
							})
					};
					tracks[list.id] = [];
					// api returns a max of 100 tracks at once, provides field "next" if there is more to come
					while (response.next) {
						// get next (up to 100) tracks
						response = JSON.parse(
							await rp
								.get({
									url:
										list.tracks.href +
										"?" +
										querystring.stringify({
											fields: "total,next,items(track(uri))"
										}),
									headers: {
										Authorization: "Bearer " + access_token
									}
								})
								.catch(err => {
									throw err;
								})
						);
						// append next tracks to arr
						tracks[list.id].push(
							...response.items.map(track => track.track.uri)
						);
					}
				}

				// update tracklist of every merged playlist
				for (let { id: merged_id, lists } of merged_lists) {
					const uris = [
						...new Set(
							lists
								.map(list => tracks[list.id])
								.reduce((acc, cur) => acc.concat(cur), [])
						)
					];
					rp.put({
						url: `https://api.spotify.com/v1/playlists/${merged_id}/tracks`,
						headers: {
							Authorization: "Bearer " + access_token,
							"Content-Type": "application/json"
						},
						body: JSON.stringify({
							uris: uris
						})
					}).catch(err => {
						throw err;
					});
				}
				console.log(`Updated ${merged_lists.length} playlists.`);
			})
			.catch(err => {
				throw err;
			});
		res.send("Merging...");
	}
});

app.get("/", (req, res, next) =>
	res.send('Hello World<br /><a href="/login">login</a>')
);

app.listen(8000, () => console.log("Server listening at port 8000"));
